apiVersion: v1
kind: Namespace
metadata:
  name: asperathos-system
---
apiVersion: v1
data:
  broker.cfg: "[general]\nhost = 0.0.0.0\nport = 1500\nplugins = kubejobs\n\n[services]\ncontroller_url
    = http://0.0.0.0:5000\nmonitor_url = http://0.0.0.0:5001\noptimizer_url = http://0.0.0.0:5002\nauthorization_url
    = http://0.0.0.0:5003\n\n[openstack_generic]\nuser = asperathos\npassword = asperathos\nauth_ip
    = https://my.openstack.cloud\nproject_id = 29380d210d98bdsc9m29jm231r901hn23\nuser_domain_name
    = asperathos\npublic_key = asperathos_key\nkey_path = /home/asperathos/.ssh/asperathos_key\nlog_path
    = /var/log/asperathos/broker \n"
kind: ConfigMap
metadata:
  name: broker-cfg-cm
  namespace: asperathos-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asperathos-serviceaccount
  namespace: asperathos-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: asperathos-system
  name: job-creator
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qos-data-analysis
  namespace: asperathos-system
subjects:
- kind: ServiceAccount
  name: asperathos-serviceaccount
  namespace: asperathos-system 
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asperathos-manager
  namespace: asperathos-system
  labels:
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      serviceAccountName: asperathos-serviceaccount
      containers:
        - name: manager
          image: 10.11.5.6:5000/asperathos:manager
          imagePullPolicy: Always
          ports:
          - containerPort: 1500
          volumeMounts:
          - name: broker-cfg
            mountPath: /usr/asperathos/conf/
      volumes:
        - name: broker-cfg
          configMap:
            name: broker-cfg-cm
---
apiVersion: v1
kind: Service
metadata:
  name: manager-svc
  namespace: asperathos-system
spec:
  selector:
    app: manager
  ports:
  - port: 80
    targetPort: 1500
    nodePort: 30171
  type: NodePort
